### ISSUE TITLE
Add CC0 License Information to OBO Foundry

### ISSUE THREAD

**Issue by dhimmel** [flora-phenotype-ontology/flopoontology#8]
The [OBO Foundry page](http://www.obofoundry.org/ontology/flopo.html) doesn't list the license. However, the [homepage](http://www.obofoundry.org/) links to an [about page for CC0](https://creativecommons.org/about/cc0) rather than the [actual license overview](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by leechuck** [comment]
Thank you, this is now updated and merged at the OBOFoundry site.
